=== l8nite/voidstar/project2/src/main/XQuery/resources/xml/Languages.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Language" type="Language"/>

  <xs:element name="Languages" type="Languages"/>

  <xs:complexType name="Languages">
    <xs:sequence>
      <xs:element ref="Language" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Language">
    <xs:sequence>
      <xs:element name="ID" type="xs:int" minOccurs="0"/>
      <xs:element name="Language" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== l8nite/voidstar/populous-ws/src/main/resources/xml/Languages.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

    This file is a component of the p.opulo.us project.

    Copyright (c) 2013 Jason Campos <jcampos8782@gmail.com>, Shaun Guth, Ash Islam
    All Rights Reserved.

    This software is licensed under The MIT License (MIT)
    http://opensource.org/licenses/MIT

-->
<dao:Languages xmlns:dao="http://p.opulo.us/dao" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="src/main/resources/xsd/dao//Languages.xsd">
    <Language>
        <ID>1</ID>
        <Language>Abhyasi</Language>
    </Language>
    <Language>
        <ID>2</ID>
        <Language>Acholi</Language>
    </Language>
    <Language>
        <ID>3</ID>
        <Language>Adja</Language>
    </Language>
    <Language>
        <ID>4</ID>
        <Language>Afar</Language>
    </Language>
    <Language>
        <ID>5</ID>
        <Language>Afrikaans</Language>
    </Language>
    <Language>
        <ID>6</ID>
        <Language>Aimarï¿½</Language>
    </Language>
    <Language>
        <ID>7</ID>
        <Language>Ainu</Language>
    </Language>
    <Language>
        <ID>8</ID>
        <Language>Aizo</Language>
    </Language>
    <Language>
        <ID>9</ID>
        <Language>Akan</Language>
    </Language>
    <Language>
        <ID>10</ID>
        <Language>Albaniana</Language>
    </Language>
    <Language>
        <ID>11</ID>
        <Language>Ambo</Language>
    </Language>
    <Language>
        <ID>12</ID>
        <Language>Amhara</Language>
    </Language>
    <Language>
        <ID>13</ID>
        <Language>Ami</Language>
    </Language>
    <Language>
        <ID>14</ID>
        <Language>Ane</Language>
    </Language>
    <Language>
        <ID>15</ID>
        <Language>Arabic</Language>
    </Language>
    <Language>
        <ID>16</ID>
        <Language>Arabic-French</Language>
    </Language>
    <Language>
        <ID>17</ID>
        <Language>Arabic-French-English</Language>
    </Language>
    <Language>
        <ID>18</ID>
        <Language>Araucan</Language>
    </Language>
    <Language>
        <ID>19</ID>
        <Language>Arawakan</Language>
    </Language>
    <Language>
        <ID>20</ID>
        <Language>Armenian</Language>
    </Language>
    <Language>
        <ID>21</ID>
        <Language>Asami</Language>
    </Language>
    <Language>
        <ID>22</ID>
        <Language>Assyrian</Language>
    </Language>
    <Language>
        <ID>23</ID>
        <Language>Atayal</Language>
    </Language>
    <Language>
        <ID>24</ID>
        <Language>Avarian</Language>
    </Language>
    <Language>
        <ID>25</ID>
        <Language>Azerbaijani</Language>
    </Language>
    <Language>
        <ID>26</ID>
        <Language>Bajad</Language>
    </Language>
    <Language>
        <ID>27</ID>
        <Language>Bajan</Language>
    </Language>
    <Language>
        <ID>28</ID>
        <Language>Bakhtyari</Language>
    </Language>
    <Language>
        <ID>29</ID>
        <Language>Balante</Language>
    </Language>
    <Language>
        <ID>30</ID>
        <Language>Bali</Language>
    </Language>
    <Language>
        <ID>31</ID>
        <Language>Balochi</Language>
    </Language>
    <Language>
        <ID>32</ID>
        <Language>Bambara</Language>
    </Language>
    <Language>
        <ID>33</ID>
        <Language>Bamileke-bamum</Language>
    </Language>
    <Language>
        <ID>34</ID>
        <Language>Banda</Language>
    </Language>
    <Language>
        <ID>35</ID>
        <Language>Banja</Language>
    </Language>
    <Language>
        <ID>36</ID>
        <Language>Bari</Language>
    </Language>
    <Language>
        <ID>37</ID>
        <Language>Bariba</Language>
    </Language>
    <Language>
        <ID>38</ID>
        <Language>Bashkir</Language>
    </Language>
    <Language>
        <ID>39</ID>
        <Language>Basque</Language>
    </Language>
    <Language>
        <ID>40</ID>
        <Language>Bassa</Language>
    </Language>
    <Language>
        <ID>41</ID>
        <Language>Batakki</Language>
    </Language>
    <Language>
        <ID>42</ID>
        <Language>Beja</Language>
    </Language>
    <Language>
        <ID>43</ID>
        <Language>Belorussian</Language>
    </Language>
    <Language>
        <ID>44</ID>
        <Language>Bemba</Language>
    </Language>
    <Language>
        <ID>45</ID>
        <Language>Bengali</Language>
    </Language>
    <Language>
        <ID>46</ID>
        <Language>Berberi</Language>
    </Language>
    <Language>
        <ID>47</ID>
        <Language>Bhojpuri</Language>
    </Language>
    <Language>
        <ID>48</ID>
        <Language>Bicol</Language>
    </Language>
    <Language>
        <ID>49</ID>
        <Language>Bilin</Language>
    </Language>
    <Language>
        <ID>50</ID>
        <Language>Bislama</Language>
    </Language>
    <Language>
        <ID>51</ID>
        <Language>Boa</Language>
    </Language>
    <Language>
        <ID>52</ID>
        <Language>Brahui</Language>
    </Language>
    <Language>
        <ID>53</ID>
        <Language>Bubi</Language>
    </Language>
    <Language>
        <ID>54</ID>
        <Language>Bugi</Language>
    </Language>
    <Language>
        <ID>55</ID>
        <Language>Bulgariana</Language>
    </Language>
    <Language>
        <ID>56</ID>
        <Language>Bullom-sherbro</Language>
    </Language>
    <Language>
        <ID>57</ID>
        <Language>Bura</Language>
    </Language>
    <Language>
        <ID>58</ID>
        <Language>Burmese</Language>
    </Language>
    <Language>
        <ID>59</ID>
        <Language>Buryat</Language>
    </Language>
    <Language>
        <ID>60</ID>
        <Language>Busansi</Language>
    </Language>
    <Language>
        <ID>61</ID>
        <Language>Cakchiquel</Language>
    </Language>
    <Language>
        <ID>62</ID>
        <Language>Canton Chinese</Language>
    </Language>
    <Language>
        <ID>63</ID>
        <Language>Caprivi</Language>
    </Language>
    <Language>
        <ID>64</ID>
        <Language>Caribbean</Language>
    </Language>
    <Language>
        <ID>65</ID>
        <Language>Carolinian</Language>
    </Language>
    <Language>
        <ID>66</ID>
        <Language>Catalan</Language>
    </Language>
    <Language>
        <ID>67</ID>
        <Language>Cebuano</Language>
    </Language>
    <Language>
        <ID>68</ID>
        <Language>Chaga and Pare</Language>
    </Language>
    <Language>
        <ID>69</ID>
        <Language>Chakma</Language>
    </Language>
    <Language>
        <ID>70</ID>
        <Language>Chamorro</Language>
    </Language>
    <Language>
        <ID>71</ID>
        <Language>Chechen</Language>
    </Language>
    <Language>
        <ID>72</ID>
        <Language>Chewa</Language>
    </Language>
    <Language>
        <ID>73</ID>
        <Language>Chibcha</Language>
    </Language>
    <Language>
        <ID>74</ID>
        <Language>Chichewa</Language>
    </Language>
    <Language>
        <ID>75</ID>
        <Language>Chilluk</Language>
    </Language>
    <Language>
        <ID>76</ID>
        <Language>Chin</Language>
    </Language>
    <Language>
        <ID>77</ID>
        <Language>Chinese</Language>
    </Language>
    <Language>
        <ID>78</ID>
        <Language>Chiu chau</Language>
    </Language>
    <Language>
        <ID>79</ID>
        <Language>Chokwe</Language>
    </Language>
    <Language>
        <ID>80</ID>
        <Language>Chuabo</Language>
    </Language>
    <Language>
        <ID>81</ID>
        <Language>Chuvash</Language>
    </Language>
    <Language>
        <ID>82</ID>
        <Language>Circassian</Language>
    </Language>
    <Language>
        <ID>83</ID>
        <Language>Comorian</Language>
    </Language>
    <Language>
        <ID>84</ID>
        <Language>Comorian-Arabic</Language>
    </Language>
    <Language>
        <ID>85</ID>
        <Language>Comorian-French</Language>
    </Language>
    <Language>
        <ID>86</ID>
        <Language>Comorian-Swahili</Language>
    </Language>
    <Language>
        <ID>87</ID>
        <Language>Comorian-madagassi</Language>
    </Language>
    <Language>
        <ID>88</ID>
        <Language>Creole English</Language>
    </Language>
    <Language>
        <ID>89</ID>
        <Language>Creole French</Language>
    </Language>
    <Language>
        <ID>90</ID>
        <Language>Crioulo</Language>
    </Language>
    <Language>
        <ID>91</ID>
        <Language>Cuna</Language>
    </Language>
    <Language>
        <ID>92</ID>
        <Language>Czech and Moravian</Language>
    </Language>
    <Language>
        <ID>93</ID>
        <Language>Czech</Language>
    </Language>
    <Language>
        <ID>94</ID>
        <Language>Dagara</Language>
    </Language>
    <Language>
        <ID>95</ID>
        <Language>Danish</Language>
    </Language>
    <Language>
        <ID>96</ID>
        <Language>Dari</Language>
    </Language>
    <Language>
        <ID>97</ID>
        <Language>Dariganga</Language>
    </Language>
    <Language>
        <ID>98</ID>
        <Language>Dhivehi</Language>
    </Language>
    <Language>
        <ID>99</ID>
        <Language>Dinka</Language>
    </Language>
    <Language>
        <ID>100</ID>
        <Language>Diola</Language>
    </Language>
    <Language>
        <ID>101</ID>
        <Language>Dong</Language>
    </Language>
    <Language>
        <ID>102</ID>
        <Language>Dorbet</Language>
    </Language>
    <Language>
        <ID>103</ID>
        <Language>Duala</Language>
    </Language>
    <Language>
        <ID>104</ID>
        <Language>Dusun</Language>
    </Language>
    <Language>
        <ID>105</ID>
        <Language>Dutch</Language>
    </Language>
    <Language>
        <ID>106</ID>
        <Language>Dyula</Language>
    </Language>
    <Language>
        <ID>107</ID>
        <Language>Dzongkha</Language>
    </Language>
    <Language>
        <ID>108</ID>
