=== l8nite/voidstar/service/src/main/XQuery/resources/xsd/Infections.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

                                  .__
    ______      ____ ______  __ __|  |   ____      __ __  ______
    \____ \    /  _ \\____ \|  |  \  |  /  _ \    |  |  \/  ___/
    |  |_> >  (  <_> )  |_> >  |  /  |_(  <_> )   |  |  /\___ \
    |   __/ /\ \____/|   __/|____/|____/\____/ /\ |____//____  >
    |__|    \/       |__|                      \/            \/


    Copyright (c) 2013 Jason Campos <jcampos8782@gmail.com>, Shaun Guth, Ash Islam
    All Rights Reserved.

    This software is licensed under The MIT License (MIT)
    http://opensource.org/licenses/MIT

-->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Infection" type="Infection"/>

  <xs:element name="Infections" type="Infections"/>

  <xs:complexType name="Infections">
    <xs:sequence>
      <xs:element ref="Infection" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Infection">
    <xs:sequence>
      <xs:element name="ID" type="xs:int" minOccurs="0"/>
      <xs:element name="CityID" type="xs:string" minOccurs="0"/>
      <xs:element name="Zombies" type="xs:int" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== l8nite/voidstar/service/src/main/XQuery/resources/xml/Infections.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

                                  .__
    ______      ____ ______  __ __|  |   ____      __ __  ______
    \____ \    /  _ \\____ \|  |  \  |  /  _ \    |  |  \/  ___/
    |  |_> >  (  <_> )  |_> >  |  /  |_(  <_> )   |  |  /\___ \
    |   __/ /\ \____/|   __/|____/|____/\____/ /\ |____//____  >
    |__|    \/       |__|                      \/            \/


    Copyright (c) 2013 Jason Campos <jcampos8782@gmail.com>, Shaun Guth, Ash Islam
    All Rights Reserved.

    This software is licensed under The MIT License (MIT)
    http://opensource.org/licenses/MIT

-->
<Infections xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="src/main/resources/xsd/Infections.xsd">
    <Infection>
        <ID>17136</ID>
        <CityID>3186</CityID>
        <Zombies>102779</Zombies>
    </Infection>
    <Infection>
        <ID>17137</ID>
        <CityID>2207</CityID>
        <Zombies>54291</Zombies>
    </Infection>
    <Infection>
        <ID>17138</ID>
        <CityID>3258</CityID>
        <Zombies>3942</Zombies>
    </Infection>
    <Infection>
        <ID>17139</ID>
        <CityID>3831</CityID>
        <Zombies>416474</Zombies>
    </Infection>
    <Infection>
        <ID>17140</ID>
        <CityID>324</CityID>
        <Zombies>178988</Zombies>
    </Infection>
    <Infection>
        <ID>17141</ID>
        <CityID>3642</CityID>
        <Zombies>65058</Zombies>
    </Infection>
    <Infection>
        <ID>17142</ID>
        <CityID>3727</CityID>
        <Zombies>31407</Zombies>
    </Infection>
    <Infection>
        <ID>17143</ID>
        <CityID>1490</CityID>
        <Zombies>93100</Zombies>
    </Infection>
    <Infection>
        <ID>17144</ID>
        <CityID>2693</CityID>
        <Zombies>62015</Zombies>
    </Infection>
    <Infection>
        <ID>17145</ID>
        <CityID>1321</CityID>
        <Zombies>57942</Zombies>
    </Infection>
    <Infection>
        <ID>17146</ID>
        <CityID>1122</CityID>
        <Zombies>172487</Zombies>
    </Infection>
    <Infection>
        <ID>17147</ID>
        <CityID>4062</CityID>
        <Zombies>83861</Zombies>
    </Infection>
    <Infection>
        <ID>17148</ID>
        <CityID>3314</CityID>
        <Zombies>64501</Zombies>
    </Infection>
    <Infection>
        <ID>17149</ID>
        <CityID>1880</CityID>
        <Zombies>90000</Zombies>
    </Infection>
    <Infection>
        <ID>17150</ID>
        <CityID>2137</CityID>
        <Zombies>148583</Zombies>
    </Infection>
    <Infection>
        <ID>17151</ID>
        <CityID>2324</CityID>
        <Zombies>92616</Zombies>
    </Infection>
    <Infection>
        <ID>17152</ID>
        <CityID>236</CityID>
        <Zombies>341752</Zombies>
    </Infection>
    <Infection>
        <ID>17153</ID>
        <CityID>1055</CityID>
        <Zombies>583971</Zombies>
    </Infection>
    <Infection>
        <ID>17154</ID>
        <CityID>3291</CityID>
        <Zombies>3228</Zombies>
    </Infection>
    <Infection>
        <ID>17155</ID>
        <CityID>2045</CityID>
        <Zombies>65814</Zombies>
    </Infection>
    <Infection>
        <ID>17156</ID>
        <CityID>34</CityID>
        <Zombies>28065</Zombies>
    </Infection>
    <Infection>
        <ID>17157</ID>
        <CityID>3249</CityID>
        <Zombies>75155</Zombies>
    </Infection>
    <Infection>
        <ID>17158</ID>
        <CityID>429</CityID>
        <Zombies>57965</Zombies>
    </Infection>
    <Infection>
        <ID>17159</ID>
        <CityID>1877</CityID>
        <Zombies>73064</Zombies>
    </Infection>
    <Infection>
        <ID>17160</ID>
        <CityID>3753</CityID>
        <Zombies>2580</Zombies>
    </Infection>
    <Infection>
        <ID>17161</ID>
        <CityID>1219</CityID>
        <Zombies>36092</Zombies>
    </Infection>
    <Infection>
        <ID>17162</ID>
        <CityID>693</CityID>
        <Zombies>17906</Zombies>
    </Infection>
    <Infection>
        <ID>17163</ID>
        <CityID>2211</CityID>
        <Zombies>108504</Zombies>
    </Infection>
    <Infection>
        <ID>17164</ID>
        <CityID>1180</CityID>
        <Zombies>33647</Zombies>
    </Infection>
    <Infection>
        <ID>17165</ID>
        <CityID>3940</CityID>
        <Zombies>26745</Zombies>
    </Infection>
    <Infection>
        <ID>17166</ID>
        <CityID>2323</CityID>
        <Zombies>247820</Zombies>
    </Infection>
    <Infection>
        <ID>17167</ID>
        <CityID>3556</CityID>
        <Zombies>5890</Zombies>
    </Infection>
    <Infection>
        <ID>17168</ID>
        <CityID>1697</CityID>
        <Zombies>43955</Zombies>
    </Infection>
    <Infection>
        <ID>17169</ID>
        <CityID>727</CityID>
        <Zombies>122523</Zombies>
    </Infection>
    <Infection>
        <ID>17170</ID>
        <CityID>2854</CityID>
        <Zombies>128959</Zombies>
    </Infection>
    <Infection>
        <ID>17171</ID>
        <CityID>3247</CityID>
        <Zombies>148046</Zombies>
    </Infection>
    <Infection>
        <ID>17172</ID>
        <CityID>1688</CityID>
        <Zombies>77415</Zombies>
    </Infection>
    <Infection>
        <ID>17173</ID>
        <CityID>1043</CityID>
        <Zombies>320273</Zombies>
    </Infection>
    <Infection>
        <ID>17174</ID>
        <CityID>145</CityID>
        <Zombies>299300</Zombies>
    </Infection>
    <Infection>
        <ID>17175</ID>
        <CityID>2423</CityID>
        <Zombies>123273</Zombies>
    </Infection>
    <Infection>
        <ID>17176</ID>
        <CityID>3272</CityID>
        <Zombies>361958</Zombies>
    </Infection>
    <Infection>
        <ID>17177</ID>
        <CityID>2892</CityID>
        <Zombies>479741</Zombies>
    </Infection>
    <Infection>
        <ID>17178</ID>
        <CityID>3381</CityID>
        <Zombies>131039</Zombies>
    </Infection>
    <Infection>
        <ID>17179</ID>
        <CityID>566</CityID>
        <Zombies>54443</Zombies>
    </Infection>
    <Infection>
        <ID>17180</ID>
        <CityID>3311</CityID>
        <Zombies>117800</Zombies>
    </Infection>
    <Infection>
        <ID>17181</ID>
        <CityID>1522</CityID>
        <Zombies>19056</Zombies>
    </Infection>
    <Infection>
        <ID>17182</ID>
        <CityID>2056</CityID>
        <Zombies>48663</Zombies>
    </Infection>
    <Infection>
        <ID>17183</ID>
        <CityID>1047</CityID>
        <Zombies>891790</Zombies>
    </Infection>
    <Infection>
        <ID>17184</ID>
        <CityID>325</CityID>
        <Zombies>177764</Zombies>
    </Infection>
    <Infection>
        <ID>17185</ID>
        <CityID>3393</CityID>
        <Zombies>5515</Zombies>
    </Infection>
    <Infection>
        <ID>17186</ID>
        <CityID>3265</CityID>
        <Zombies>55054</Zombies>
    </Infection>
    <Infection>
        <ID>17187</ID>
        <CityID>649</CityID>
        <Zombies>125902</Zombies>
    </Infection>
    <Infection>
        <ID>17188</ID>
        <CityID>2492</CityID>
        <Zombies>136639</Zombies>
    </Infection>
    <Infection>
        <ID>17189</ID>
        <CityID>1102</CityID>
        <Zombies>287874</Zombies>
    </Infection>
    <Infection>
        <ID>17190</ID>
        <CityID>1513</CityID>
        <Zombies>77940</Zombies>
    </Infection>
    <Infection>
        <ID>17191</ID>
        <CityID>2682</CityID>
        <Zombies>64476</Zombies>
    </Infection>
    <Infection>
        <ID>17192</ID>
        <CityID>185</CityID>
        <Zombies>1313</Zombies>
    </Infection>
    <Infection>
        <ID>17193</ID>
        <CityID>2753</CityID>
        <Zombies>56175</Zombies>
    </Infection>
    <Infection>
        <ID>17194</ID>
        <CityID>898</CityID>
        <Zombies>10900</Zombies>
    </Infection>
    <Infection>
        <ID>17195</ID>
        <CityID>1201</CityID>
        <Zombies>52978</Zombies>
    </Infection>
    <Infection>
        <ID>17196</ID>
        <CityID>2651</CityID>
        <Zombies>16480</Zombies>
    </Infection>
    <Infection>
        <ID>17197</ID>
        <CityID>512</CityID>
        <Zombies>106000</Zombies>
    </Infection>
    <Infection>
        <ID>17198</ID>
        <CityID>65</CityID>
        <Zombies>295415</Zombies>
    </Infection>
    <Infection>
        <ID>17199</ID>
        <CityID>3382</CityID>
        <Zombies>180709</Zombies>
    </Infection>
    <Infection>
        <ID>17200</ID>
        <CityID>3207</CityID>
        <Zombies>424888</Zombies>
    </Infection>
    <Infection>
        <ID>17201</ID>
        <CityID>853</CityID>
        <Zombies>31815</Zombies>
    </Infection>
    <Infection>
        <ID>17202</ID>
        <CityID>2433</CityID>
        <Zombies>60928</Zombies>
    </Infection>
    <Infection>
        <ID>17203</ID>
        <CityID>1010</CityID>
        <Zombies>51775</Zombies>
    </Infection>
    <Infection>
        <ID>17204</ID>
        <CityID>2793</CityID>
        <Zombies>114098</Zombies>
    </Infection>
    <Infection>
        <ID>17205</ID>
        <CityID>398</CityID>
        <Zombies>38585</Zombies>
    </Infection>
    <Infection>
        <ID>17206</ID>
        <CityID>1394</CityID>
        <Zombies>228561</Zombies>
    </Infection>
    <Infection>
        <ID>17207</ID>
        <CityID>3224</CityID>
        <Zombies>1099937</Zombies>
    </Infection>
    <Infection>
        <ID>17208</ID>
        <CityID>1345</CityID>
        <Zombies>68613</Zombies>
    </Infection>
    <Infection>
        <ID>17209</ID>
        <CityID>2208</CityID>
        <Zombies>24444</Zombies>
    </Infection>
    <Infection>
        <ID>17210</ID>
        <CityID>1728</CityID>
        <Zombies>111666</Zombies>
    </Infection>
    <Infection>
        <ID>17211</ID>
        <CityID>3144</CityID>
        <Zombies>106150</Zombies>
    </Infection>
    <Infection>
        <ID>17212</ID>
        <CityID>1327</CityID>
        <Zombies>39795</Zombies>
    </Infection>
    <Infection>
        <ID>17213</ID>
