=== l8nite/voidstar/project2/src/main/resources/xsd/Countries.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Countries" type="Countries"/>

  <xs:element name="Country" type="Country"/>

  <xs:complexType name="Countries">
    <xs:sequence>
      <xs:element ref="Country" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Country">
    <xs:sequence>
      <xs:element name="Code" type="xs:string" minOccurs="0"/>
      <xs:element name="Name" type="xs:string" minOccurs="0"/>
      <xs:element name="Continent" type="xs:string" minOccurs="0"/>
      <xs:element name="Region" type="xs:string" minOccurs="0"/>
      <xs:element name="SurfaceArea" type="xs:float" minOccurs="0"/>
      <xs:element name="IndepYear" type="xs:int" minOccurs="0"/>
      <xs:element name="Population" type="xs:int" minOccurs="0"/>
      <xs:element name="LifeExpectancy" type="xs:int" minOccurs="0"/>
      <xs:element name="GNP" type="xs:float" minOccurs="0"/>
      <xs:element name="GNPOld" type="xs:float" minOccurs="0"/>
      <xs:element name="LocalName" type="xs:string" minOccurs="0"/>
      <xs:element name="GovernmentForm" type="xs:string" minOccurs="0"/>
      <xs:element name="HeadOfState" type="xs:string" minOccurs="0"/>
      <xs:element name="Capital" type="xs:int" minOccurs="0"/>
      <xs:element name="Code2" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== l8nite/voidstar/service/src/main/resources/xml/Countries.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

                                  .__
    ______      ____ ______  __ __|  |   ____      __ __  ______
    \____ \    /  _ \\____ \|  |  \  |  /  _ \    |  |  \/  ___/
    |  |_> >  (  <_> )  |_> >  |  /  |_(  <_> )   |  |  /\___ \
    |   __/ /\ \____/|   __/|____/|____/\____/ /\ |____//____  >
    |__|    \/       |__|                      \/            \/


    Copyright (c) 2013 Jason Campos <jcampos8782@gmail.com>, Shaun Guth, Ash Islam
    All Rights Reserved.

    This software is licensed under The MIT License (MIT)
    http://opensource.org/licenses/MIT

-->
<dao:Countries xmlns:dao="http://p.opulo.us/dao" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="src/main/resources/xsd/dao//Countries.xsd">
    <Country>
        <Code>ABW</Code>
        <Name>Aruba</Name>
        <Continent>North America</Continent>
        <Region>Caribbean</Region>
        <SurfaceArea>193.0</SurfaceArea>
        <Population>103000</Population>
        <LifeExpectancy>78</LifeExpectancy>
        <GNP>828.0</GNP>
        <GNPOld>793.0</GNPOld>
        <LocalName>Aruba</LocalName>
        <GovernmentForm>Nonmetropolitan Territory of The Netherlands</GovernmentForm>
        <HeadOfState>Beatrix</HeadOfState>
        <Capital>129</Capital>
        <Code2>AW</Code2>
    </Country>
    <Country>
        <Code>AFG</Code>
        <Name>Afghanistan</Name>
        <Continent>Asia</Continent>
        <Region>Southern and Central Asia</Region>
        <SurfaceArea>652090.0</SurfaceArea>
        <IndepYear>1919</IndepYear>
        <Population>22720000</Population>
        <LifeExpectancy>45</LifeExpectancy>
        <GNP>5976.0</GNP>
        <LocalName>Afganistan/Afqanestan</LocalName>
        <GovernmentForm>Islamic Emirate</GovernmentForm>
        <HeadOfState>Mohammad Omar</HeadOfState>
        <Capital>1</Capital>
        <Code2>AF</Code2>
    </Country>
    <Country>
        <Code>AGO</Code>
        <Name>Angola</Name>
        <Continent>Africa</Continent>
        <Region>Central Africa</Region>
        <SurfaceArea>1246700.0</SurfaceArea>
        <IndepYear>1975</IndepYear>
        <Population>12878000</Population>
        <LifeExpectancy>38</LifeExpectancy>
        <GNP>6648.0</GNP>
        <GNPOld>7984.0</GNPOld>
        <LocalName>Angola</LocalName>
        <GovernmentForm>Republic</GovernmentForm>
        <HeadOfState>Josï¿½ Eduardo dos Santos</HeadOfState>
        <Capital>56</Capital>
        <Code2>AO</Code2>
    </Country>
    <Country>
        <Code>AIA</Code>
        <Name>Anguilla</Name>
        <Continent>North America</Continent>
        <Region>Caribbean</Region>
        <SurfaceArea>96.0</SurfaceArea>
        <Population>8000</Population>
        <LifeExpectancy>76</LifeExpectancy>
        <GNP>63.2</GNP>
        <LocalName>Anguilla</LocalName>
        <GovernmentForm>Dependent Territory of the UK</GovernmentForm>
        <HeadOfState>Elisabeth II</HeadOfState>
        <Capital>62</Capital>
        <Code2>AI</Code2>
    </Country>
    <Country>
        <Code>ALB</Code>
        <Name>Albania</Name>
        <Continent>Europe</Continent>
        <Region>Southern Europe</Region>
        <SurfaceArea>28748.0</SurfaceArea>
        <IndepYear>1912</IndepYear>
        <Population>3401200</Population>
        <LifeExpectancy>71</LifeExpectancy>
        <GNP>3205.0</GNP>
        <GNPOld>2500.0</GNPOld>
        <LocalName>Shqipï¿½ria</LocalName>
        <GovernmentForm>Republic</GovernmentForm>
        <HeadOfState>Rexhep Mejdani</HeadOfState>
        <Capital>34</Capital>
        <Code2>AL</Code2>
    </Country>
    <Country>
        <Code>AND</Code>
        <Name>Andorra</Name>
        <Continent>Europe</Continent>
        <Region>Southern Europe</Region>
        <SurfaceArea>468.0</SurfaceArea>
        <IndepYear>1278</IndepYear>
        <Population>78000</Population>
        <LifeExpectancy>83</LifeExpectancy>
        <GNP>1630.0</GNP>
        <LocalName>Andorra</LocalName>
        <GovernmentForm>Parliamentary Coprincipality</GovernmentForm>
        <HeadOfState></HeadOfState>
        <Capital>55</Capital>
        <Code2>AD</Code2>
    </Country>
    <Country>
        <Code>ANT</Code>
        <Name>Netherlands Antilles</Name>
        <Continent>North America</Continent>
        <Region>Caribbean</Region>
        <SurfaceArea>800.0</SurfaceArea>
        <Population>217000</Population>
        <LifeExpectancy>74</LifeExpectancy>
        <GNP>1941.0</GNP>
        <LocalName>Nederlandse Antillen</LocalName>
        <GovernmentForm>Nonmetropolitan Territory of The Netherlands</GovernmentForm>
        <HeadOfState>Beatrix</HeadOfState>
        <Capital>33</Capital>
        <Code2>AN</Code2>
    </Country>
    <Country>
        <Code>ARE</Code>
        <Name>United Arab Emirates</Name>
        <Continent>Asia</Continent>
        <Region>Middle East</Region>
        <SurfaceArea>83600.0</SurfaceArea>
        <IndepYear>1971</IndepYear>
        <Population>2441000</Population>
        <LifeExpectancy>74</LifeExpectancy>
        <GNP>37966.0</GNP>
        <GNPOld>36846.0</GNPOld>
        <LocalName>Al-Imarat al-ï¿½Arabiya al-Muttahida</LocalName>
        <GovernmentForm>Emirate Federation</GovernmentForm>
        <HeadOfState>Zayid bin Sultan al-Nahayan</HeadOfState>
        <Capital>65</Capital>
        <Code2>AE</Code2>
    </Country>
    <Country>
        <Code>ARG</Code>
        <Name>Argentina</Name>
        <Continent>South America</Continent>
        <Region>South America</Region>
        <SurfaceArea>2780400.0</SurfaceArea>
        <IndepYear>1816</IndepYear>
        <Population>37032000</Population>
        <LifeExpectancy>75</LifeExpectancy>
        <GNP>340238.0</GNP>
        <GNPOld>323310.0</GNPOld>
        <LocalName>Argentina</LocalName>
        <GovernmentForm>Federal Republic</GovernmentForm>
        <HeadOfState>Fernando de la Rï¿½a</HeadOfState>
        <Capital>69</Capital>
        <Code2>AR</Code2>
    </Country>
    <Country>
        <Code>ARM</Code>
        <Name>Armenia</Name>
        <Continent>Asia</Continent>
        <Region>Middle East</Region>
        <SurfaceArea>29800.0</SurfaceArea>
        <IndepYear>1991</IndepYear>
        <Population>3520000</Population>
        <LifeExpectancy>66</LifeExpectancy>
        <GNP>1813.0</GNP>
        <GNPOld>1627.0</GNPOld>
        <LocalName>Hajastan</LocalName>
        <GovernmentForm>Republic</GovernmentForm>
        <HeadOfState>Robert Kotï¿½arjan</HeadOfState>
        <Capital>126</Capital>
        <Code2>AM</Code2>
    </Country>
    <Country>
        <Code>ASM</Code>
        <Name>American Samoa</Name>
        <Continent>Oceania</Continent>
        <Region>Polynesia</Region>
        <SurfaceArea>199.0</SurfaceArea>
        <Population>68000</Population>
        <LifeExpectancy>75</LifeExpectancy>
        <GNP>334.0</GNP>
        <LocalName>Amerika Samoa</LocalName>
        <GovernmentForm>US Territory</GovernmentForm>
        <HeadOfState>George W. Bush</HeadOfState>
        <Capital>54</Capital>
        <Code2>AS</Code2>
    </Country>
    <Country>
        <Code>ATA</Code>
        <Name>Antarctica</Name>
        <Continent>Antarctica</Continent>
        <Region>Antarctica</Region>
        <SurfaceArea>1.312E7</SurfaceArea>
        <Population>0</Population>
        <GNP>0.0</GNP>
        <LocalName>ï¿½</LocalName>
        <GovernmentForm>Co-administrated</GovernmentForm>
        <HeadOfState></HeadOfState>
        <Code2>AQ</Code2>
    </Country>
    <Country>
        <Code>ATF</Code>
        <Name>French Southern territories</Name>
        <Continent>Antarctica</Continent>
        <Region>Antarctica</Region>
        <SurfaceArea>7780.0</SurfaceArea>
        <Population>0</Population>
        <GNP>0.0</GNP>
        <LocalName>Terres australes franï¿½aises</LocalName>
        <GovernmentForm>Nonmetropolitan Territory of France</GovernmentForm>
        <HeadOfState>Jacques Chirac</HeadOfState>
        <Code2>TF</Code2>
    </Country>
    <Country>
        <Code>ATG</Code>
        <Name>Antigua and Barbuda</Name>
        <Continent>North America</Continent>
        <Region>Caribbean</Region>
        <SurfaceArea>442.0</SurfaceArea>
        <IndepYear>1981</IndepYear>
        <Population>68000</Population>
        <LifeExpectancy>70</LifeExpectancy>
        <GNP>612.0</GNP>
        <GNPOld>584.0</GNPOld>
        <LocalName>Antigua and Barbuda</LocalName>
        <GovernmentForm>Constitutional Monarchy</GovernmentForm>
        <HeadOfState>Elisabeth II</HeadOfState>
        <Capital>63</Capital>
        <Code2>AG</Code2>
    </Country>
    <Country>
        <Code>AUS</Code>
        <Name>Australia</Name>
        <Continent>Oceania</Continent>
        <Region>Australia and New Zealand</Region>
        <SurfaceArea>7741220.0</SurfaceArea>
        <IndepYear>1901</IndepYear>
        <Population>18886000</Population>
        <LifeExpectancy>79</LifeExpectancy>
        <GNP>351182.0</GNP>
        <GNPOld>392911.0</GNPOld>
        <LocalName>Australia</LocalName>
        <GovernmentForm>Constitutional Monarchy, Federation</GovernmentForm>
        <HeadOfState>Elisabeth II</HeadOfState>
        <Capital>135</Capital>
        <Code2>AU</Code2>
    </Country>
    <Country>
        <Code>AUT</Code>
        <Name>Austria</Name>
        <Continent>Europe</Continent>
        <Region>Western Europe</Region>
        <SurfaceArea>83859.0</SurfaceArea>
        <IndepYear>1918</IndepYear>
        <Population>8091800</Population>
        <LifeExpectancy>77</LifeExpectancy>
        <GNP>211860.0</GNP>
        <GNPOld>206025.0</GNPOld>
        <LocalName>ï¿½sterreich</LocalName>
        <GovernmentForm>Federal Republic</GovernmentForm>
        <HeadOfState>Thomas Klestil</HeadOfState>
        <Capital>1523</Capital>
        <Code2>AT</Code2>
    </Country>
    <Country>
        <Code>AZE</Code>
        <Name>Azerbaijan</Name>
        <Continent>Asia</Continent>
        <Region>Middle East</Region>
